SELECT FROM products WHERE Price BETWEEN 10 AND 20;
SELECT FROM products WHERE Price NOT BETWEEN 10 AND 20;
SELECT FROM products WHERE category_id IN (1,2,3);
SELECT FROM products WHERE shipper_id IN (1,2,3);
SELECT FROM products WHERE price BETWEEN 10 AND 15  
SELECT * FROM orders WHERE order_date BETWEEN '1996-07-01' AND '1996-07-31';
SELECT * FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE id BETWEEN 77 AND 90);
